<a href="https://colab.research.google.com/github/sayanarajasekhar/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

### What is PyTorch ?
[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework.

### What can PyTorch be used for ?
PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.



In [12]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Intoduction to tensors

Tensors are the fundamental building blocks of machine learning.

Their job is to represent data in a numerical way.

For Example, you could represent an image as a tensor with shape ```[3, 224, 224]``` which would mean ```[color_channels, height, width]```

## Creating tensors
> Documentaion on [tensers](https://docs.pytorch.org/docs/stable/tensors.html)

Lets create a **scalar**

### Scalar
A scalar is a single number and in tensor-speak it's a zero dimension tensor

In [13]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

This means although  ```scalar``` is a single number, its of type ```torch.tensor```

Lets check te dimensions of a tensor using ```ndim``` attribute

In [14]:
scalar.ndim

0

What if we want to retriece the number from the tensor ?

As in, turn it from  ```torch.tensor``` to a python integer?

To do we can use ```item()``` method


In [15]:
# Get the python number within a tensor (Only works with one-element tensors)
scalar.item()

7

### Vector

A vector is a single dimension tensor but can contain many numbers.

As in, you can have a vector ```[3, 2]``` to describe ```[bedrooms, bathrooms]``` in a house. Or you could have ```[3, 2, 2]``` to describe ```[bedrooms, bathrooms, car_parks]``` in a house.

The important trend here is that a vector is flexible in what it can reporesent

In [16]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [17]:
# Check number of dimensions of vector
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

### Matrix

Matrices are as flexible as vectors, except they got an extra dimension

In [19]:
# MATRIX

MATRIX = torch.tensor([[2, 3],
                       [4, 5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [20]:
# Check number of dimensions

MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

Tensar has more dimensions. Matrix++

In [22]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7,8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
# Check number of dimension and shape
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

### Summary


| Name | What is it? | Number of dimensions | Lower or upper <br>(usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) |
| **vector** | a number with direction (e.g. wind <br> speed with direction) but can also <br> have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, <br> a 0-dimension tensor is a scalar, <br> a 1-dimension tensor is a vector | Upper (`X`) |

## Random tensors

Machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [24]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8381, 0.9995, 0.4943, 0.0728],
         [0.5838, 0.2150, 0.9001, 0.7122],
         [0.2557, 0.2883, 0.6937, 0.4541]]),
 torch.float32)

In [25]:
# Create a random tensor of size (224, 224, 3)

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

Sometimes you'll just want to fill tensors with zeros or ones.

In [26]:
# Create a tensor with all zeros

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 torch.Size([3, 4]))

In [97]:
# Creata a tensor with all ones

ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a range tensor

Use `torch.arange(start, end, step)` to create a range tensor

Where

- `start` = start of range (e.g 0)
- `end` = end of range (e.g 10)
- `step` = how many steps in between each step (e.g 2 for 2 steps)

In [99]:
# Create a tensor of values 0 to 10

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshaping, View, Stacking, Squeezing and Unsqueezing, Permute tensors

* Reshaping - Reshape an input tensor to a defined shape. (Reshape should be compatable with original tensor size)
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor (Tensor Reference). (View should be compatable with original tensor size)
* Stacking - Concatenate a sequence of tensors along a new dimension. Combine multipe tensors on top of each other (stack, vstack - verical stack or hstack - horizental stack).
* Squeeze - Remove `1` dimension from a tensor.
* Unsqueezing - Addd `1` dimension to a target tensor.
* Permute - Return a view of input with dimensions permuted (swapped) in a certain way.

In [27]:
# Let's create a tensor

import torch
x = torch.arange(1., 10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### Reshape

In [28]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # we are trying to squze 9 element tensor to 7 elements
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [29]:
x_reshaped = x.reshape(1, 9) # we are matching elements with x tensor elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [30]:
x_reshaped = x.reshape(2, 9) # we are trying to reshape 2 * 9 elements when x has only 9 elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [32]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [33]:
x = torch.arange(1., 11.) # now x has 10 elements
x_reshaped = x.reshape(5, 2) # this will work since 5 * 2 = 10 which is equal to the elements in original tensor
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

### View

In [34]:
# Change the view
x = torch.arange(1., 10.)
z = x.view(3, 3) # Even view should match elements in original tensor
x, x.shape, z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [55]:
z[0][0] = 5
x, z # Since z is a reference tensor, changes made to view will reflect in original tensor as well

(tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[5],
          [2],
          [3]],
 
         [[4],
          [5],
          [6]],
 
         [[7],
          [8],
          [9]]]))

### Stack

In [56]:
# Stack tensors on top of each other
y = torch.stack([x, x, x, x], dim=0)
z = torch.vstack([x, x, x, x])
y, z

(tensor([[[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]),
 tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [57]:
y = torch.stack([x, x, x, x], dim=1)
y

tensor([[[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [58]:
y = torch.cat([x, x, x, x], dim= 0)
z = torch.hstack([x, x, x, x])
y, z

(tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [5, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [5, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

### Squeeze

In [59]:
# Squeeze
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [60]:
z = x_reshaped.squeeze() # Squeeze has no effect since we dont have any empty dimension
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [61]:
x_reshaped_1 = x.reshape(1, 9)
x_reshaped_1, x_reshaped_1.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [62]:
z = x_reshaped_1.squeeze() # Squeeze removed empty dimension which is empty
z, z.shape # observe the shape after squeeze. removed all singe dimensions. ex:- (2, 1) -> 2, (2, 1, 2, 1, 2) -> (2, 2, 2)

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [63]:
print(f"Original tensor: {x_reshaped_1}")
print(f"Original tensor shape: {x_reshaped_1.shape}")
print()
print(f"Squeezed tensor: {z}")
print(f"Squeezed tensor shape: {z.shape}")

Original tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Original tensor shape: torch.Size([1, 9])

Squeezed tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Squeezed tensor shape: torch.Size([9])


In [64]:
a = torch.zeros([2, 1, 2, 1, 2])
a, a.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [65]:
b = a.squeeze();
b, b.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

### Unsqueeze

Adds a single dimension to a target tensor at a specific dimension

In [93]:
print(f"Previous squeezed tensor: {z}")
print(f"Previous squeezed tensor shape: {z.shape}")

Previous squeezed tensor: tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
Previous squeezed tensor shape: torch.Size([3, 3, 1])


In [94]:
# Add an extra dimension with unsqueeze
z_unsqueezed = z.unsqueeze(dim=0)

print(f"Unsqueezed tensor at dim 0: {z_unsqueezed}")
print(f"Unsqueezed tensor shape: {z_unsqueezed.shape}")

Unsqueezed tensor at dim 0: tensor([[[[1],
          [2],
          [3]],

         [[4],
          [5],
          [6]],

         [[7],
          [8],
          [9]]]])
Unsqueezed tensor shape: torch.Size([1, 3, 3, 1])


In [95]:
# Add an extra dimension at 1 with unsqueeze
z_unsqueezed_1 = z.unsqueeze(dim=1)

print(f"Unsqueezed tensor at dim 1: {z_unsqueezed_1}")
print(f"Unsqueezed tensor shape: {z_unsqueezed_1.shape}")

Unsqueezed tensor at dim 1: tensor([[[[1],
          [2],
          [3]]],


        [[[4],
          [5],
          [6]]],


        [[[7],
          [8],
          [9]]]])
Unsqueezed tensor shape: torch.Size([3, 1, 3, 1])


In [96]:
# Add an extra dimension at 2 with unsqueeze
z_unsqueezed_2 = z.unsqueeze(dim=2)
z_unsqueezed_2, z_unsqueezed_2.shape

(tensor([[[[1]],
 
          [[2]],
 
          [[3]]],
 
 
         [[[4]],
 
          [[5]],
 
          [[6]]],
 
 
         [[[7]],
 
          [[8]],
 
          [[9]]]]),
 torch.Size([3, 3, 1, 1]))

### Permute

Rearranges the dimesions of a target tensor in a specified order - Returns a view of the original tensor with its dimensions permuted
`original tensor shape remains the same`

Reshape - Will not change the original tensor. Return new tensor with different shape `original tensor shape remains the same`

View - Will change the original tensor values. Return a refernce to the original tensor with different shape or same shape. `Original tensor shape remains the same`


Common places `permute` is used in images



In [70]:
x = torch.randn(3, 3)
x

tensor([[-2.6783,  0.9712, -0.2373],
        [ 0.8641, -0.7903,  0.1154],
        [-0.8905, -1.4119,  1.8227]])

In [71]:
z = torch.permute(x, (1, 0))
z

tensor([[-2.6783,  0.8641, -0.8905],
        [ 0.9712, -0.7903, -1.4119],
        [-0.2373,  0.1154,  1.8227]])

In [72]:
z[0][0] = 9.9999
x, z

(tensor([[ 9.9999,  0.9712, -0.2373],
         [ 0.8641, -0.7903,  0.1154],
         [-0.8905, -1.4119,  1.8227]]),
 tensor([[ 9.9999,  0.8641, -0.8905],
         [ 0.9712, -0.7903, -1.4119],
         [-0.2373,  0.1154,  1.8227]]))

In [73]:
x = torch.randn(2, 3, 5)
print(x.shape)
z = torch.permute(x, (2, 0 , 1))
print(z.shape)
# (2, 3 ,5) -> (2, 0 , 1) ->
# 2'nd index in original should move to 0,
# 0'th index in orifianl should move to 1,
# 1'st index in original should move to 2

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [74]:
x_image = torch.rand(size=(224, 220, 3)) # [height, width, colour_channel]

# Permute the original image tensor to rearrange the axis (or dim order)
# Change original [height, width, colour_channel] -> [colour_channel, height, width]

x_permuted_image = torch.permute(x_image, (2, 0 , 1)) # [colour_channel, height, width]
print(f"Shape of the image tensor: {x_image.shape}")
print(f"\nShape of the permuted image tensor: {x_permuted_image.shape}")

Shape of the image tensor: torch.Size([224, 220, 3])

Shape of the permuted image tensor: torch.Size([3, 224, 220])


## Indexing ( Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [75]:
# Create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0][1]

tensor([4, 5, 6])

In [78]:
x[0][1][2]

tensor(6)

In [79]:
z = x.reshape(3, 3, 1)
z

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [80]:
z[0]

tensor([[1],
        [2],
        [3]])

In [81]:
z[0][1]

tensor([2])

In [82]:
z[0][1][0]

tensor(2)

In [83]:
y = x.reshape(3, 1, 3)
y

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [84]:
y[2]

tensor([[7, 8, 9]])

In [85]:
y[2][0][1]

tensor(8)

### You can also use `:` to select `all` of a target dimension

In [86]:
y[1, 0, :]

tensor([4, 5, 6])

In [87]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [88]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [89]:
# Get all values of 0th and 1st dimension but only the 1 index value of 2nd dimension
x[:, 1, 1], x[0][1][1] # x[:, 1, 1] === x[0][1][1]

(tensor([5]), tensor(5))

In [90]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimesion
x[0, 0, :], x[0][0] # x[0, 0, :] === x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [91]:
# Index on x to return 9
# tensor([[[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]])

x[:, 2, 2], x[0][2][2]

(tensor([9]), tensor(9))

In [92]:
# Index on x to return 3, 6, 9
# tensor([[[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]])

x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch Tensors & NumPy

NumPy is a popular scientific python numerical computing library.

Because of this, PyTorch has functionality to interact with NumPy.

* Data in NumPy array, convert to PyTorch Tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> NumPy -> `torch.numpy()`


In [53]:
# Numpy array to PyTorch tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
print(f"Numpy array: {array}")
print(f"Numpy array type: {array.dtype}")

# Warning: When converting from numpy -> pytorch,
# pytorch reflects numpy's default datatype float64
tensor = torch.from_numpy(array)
print(f"\nTensor: {tensor}")
print(f"Tensor type: {tensor.dtype}")

# Converting tensor to float32. Since torch default datatype is float32
tensor_32 = torch.from_numpy(array).type(torch.float32)
print(f"\nTensor: {tensor_32}")
print(f"Tensor type: {tensor_32.dtype}")

Numpy array: [1. 2. 3. 4. 5. 6. 7.]
Numpy array type: float64

Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Tensor type: torch.float64

Tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Tensor type: torch.float32


In [54]:
# PyTorch tensor to NumPy array
tensor = torch.randn(10)
print(f"Tensor: {tensor}")
print(f"Tensor type: {tensor.dtype}")

array = tensor.numpy()
print(f"\nNumpy array: {array}")
print(f"Numpy array type: {array.dtype}")

Tensor: tensor([-1.1379,  0.1162,  0.7253,  1.3448,  0.2865,  0.6264, -0.0436,  0.3656,
        -0.0865,  0.5014])
Tensor type: torch.float32

Numpy array: [-1.1379185   0.11624096  0.7252549   1.3447931   0.28650224  0.62640613
 -0.04358715  0.365604   -0.08652893  0.5013713 ]
Numpy array type: float32


## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random number -> perform tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural netowoks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.



In [ ]:
import torch

# Create tow random tensors
random_tensor_a = torch.rand(3, 4) # always creates a random numbers when the cell is executed
random_tensor_b = torch.rand(3, 4)

print(f"Tensor A: \n{random_tensor_a}")
print(f"\nTensor B: \n{random_tensor_b}")
print(f"\nTensor A == Tensor B: \n{random_tensor_a == random_tensor_b}")


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42 # Can set to any number
torch.manual_seed(RANDOM_SEED)
# Create tensor with random seed
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(f"Tensor C: \n{random_tensor_c}")
print(f"\nTensor D: \n{random_tensor_d}")
print(f"\nTensor C == Tensor D: \n{random_tensor_c == random_tensor_d}")

## Running tensors and PyTorch objects on GPUs (Making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

1. Getting a GPU - Colab pro or use your own GPU or used colud computing (GCP, AWS, Azure)

In [ ]:
!nvidia-smi

### Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

### Setup device agnostic code

In [ ]:
device = "cude" if torch.cuda.is_available() else "cpu"
device

### Count number of devices

In [ ]:
torch.cuda.device_count()

## Putting tensors and models on the GPU

The reason we want our tensors/ models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on CPU)

import torch

tensor = torch.tensor([1, 2, 3], device = 'cpu')
tensor1 = torch.tensor([4, 5, 6]) # default device is CPU

print(tensor, tensor.device)
print(tensor1, tensor1.device)

In [ ]:
# Move tensor to GPU (if available) - Changed the run setting in colab to use GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu1 = tensor1.to(device)

print(tensor_on_gpu.device, tensor_on_gpu1.device)

## Moving tensors back to CPU

If tensor is on GPU, can't transfter it to NumPy

In [ ]:
tensor_on_gpu.numpy()

To fix the GPU tensor with NumPy issue, we fist set it to CPU

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
tensor_on_gpu