<a href="https://colab.research.google.com/github/sayanarajasekhar/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

### What is PyTorch ?
[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework.

### What can PyTorch be used for ?
PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Intoduction to tensors

Tensors are the fundamental building blocks of machine learning.

Their job is to represent data in a numerical way.

For Example, you could represent an image as a tensor with shape ```[3, 224, 224]``` which would mean ```[color_channels, height, width]```

## Creating tensors
> Documentaion on [tensers](https://docs.pytorch.org/docs/stable/tensors.html)

Lets create a **scalar**

### Scalar
A scalar is a single number and in tensor-speak it's a zero dimension tensor

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

This means although  ```scalar``` is a single number, its of type ```torch.tensor```

Lets check te dimensions of a tensor using ```ndim``` attribute

In [ ]:
scalar.ndim

0

What if we want to retriece the number from the tensor ?

As in, turn it from  ```torch.tensor``` to a python integer?

To do we can use ```item()``` method


In [ ]:
# Get the python number within a tensor (Only works with one-element tensors)
scalar.item()

7

### Vector

A vector is a single dimension tensor but can contain many numbers.

As in, you can have a vector ```[3, 2]``` to describe ```[bedrooms, bathrooms]``` in a house. Or you could have ```[3, 2, 2]``` to describe ```[bedrooms, bathrooms, car_parks]``` in a house.

The important trend here is that a vector is flexible in what it can reporesent

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Check number of dimensions of vector
vector.ndim

1

## Reshaping, View, Stacking, Squeezing and Unsqueezing, Permute tensors

* Reshaping - Reshape an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor (Tensor Reference).
* Stacking - Concatenate a sequence of tensors along a new dimension. Combine multipe tensors on top of each other (stack, vstack - verical stack or hstack - horizental stack).
* Squeeze - Remove `1` dimension from a tensor.
* Unsqueezing - Addd `1` dimension to a target tensor.
* Permute - Return a view of input with dimensions permuted (swapped) in a certain way.

In [1]:
# Let's create a tensor
import torch
x = torch.arange(1., 10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # we are trying to squze 9 element tensor to 7 elements
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [3]:
x_reshaped = x.reshape(1, 9) # we are matching elements with x tensor elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
x_reshaped = x.reshape(2, 9) # we are trying to reshape 2 * 9 elements when x has only 9 elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

RuntimeError: shape '[2, 9]' is invalid for input of size 9