<a href="https://colab.research.google.com/github/sayanarajasekhar/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

### What is PyTorch ?
[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework.

### What can PyTorch be used for ?
PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Intoduction to tensors

Tensors are the fundamental building blocks of machine learning.

Their job is to represent data in a numerical way.

For Example, you could represent an image as a tensor with shape ```[3, 224, 224]``` which would mean ```[color_channels, height, width]```

## Creating tensors
> Documentaion on [tensers](https://docs.pytorch.org/docs/stable/tensors.html)

Lets create a **scalar**

### Scalar
A scalar is a single number and in tensor-speak it's a zero dimension tensor

In [10]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

This means although  ```scalar``` is a single number, its of type ```torch.tensor```

Lets check te dimensions of a tensor using ```ndim``` attribute

In [11]:
scalar.ndim

0

What if we want to retriece the number from the tensor ?

As in, turn it from  ```torch.tensor``` to a python integer?

To do we can use ```item()``` method


In [12]:
# Get the python number within a tensor (Only works with one-element tensors)
scalar.item()

7

### Vector

A vector is a single dimension tensor but can contain many numbers.

As in, you can have a vector ```[3, 2]``` to describe ```[bedrooms, bathrooms]``` in a house. Or you could have ```[3, 2, 2]``` to describe ```[bedrooms, bathrooms, car_parks]``` in a house.

The important trend here is that a vector is flexible in what it can reporesent

In [13]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
# Check number of dimensions of vector
vector.ndim

1

## Reshaping, View, Stacking, Squeezing and Unsqueezing, Permute tensors

* Reshaping - Reshape an input tensor to a defined shape. (Reshape should be compatable with original tensor size)
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor (Tensor Reference). (View should be compatable with original tensor size)
* Stacking - Concatenate a sequence of tensors along a new dimension. Combine multipe tensors on top of each other (stack, vstack - verical stack or hstack - horizental stack).
* Squeeze - Remove `1` dimension from a tensor.
* Unsqueezing - Addd `1` dimension to a target tensor.
* Permute - Return a view of input with dimensions permuted (swapped) in a certain way.

In [1]:
# Let's create a tensor
import torch
x = torch.arange(1., 10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### Reshape

In [2]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # we are trying to squze 9 element tensor to 7 elements
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [3]:
x_reshaped = x.reshape(1, 9) # we are matching elements with x tensor elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
x_reshaped = x.reshape(2, 9) # we are trying to reshape 2 * 9 elements when x has only 9 elements
x_reshaped, x_reshaped.shape # Obsesrve the change in tensor shape from [9] -> [1, 9]

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [5]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [7]:
x = torch.arange(1., 11.) # now x has 10 elements
x_reshaped = x.reshape(5, 2) # this will work since 5 * 2 = 10 which is equal to the elements in original tensor
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

### View

In [22]:
# Change the view
x = torch.arange(1., 10.)
z = x.view(3, 3) # Even view should match elements in original tensor
x, x.shape, z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [23]:
z[0][0] = 5
x, z # Since z is a reference tensor, changes made to view will reflect in original tensor as well

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

### Stack

In [26]:
# Stack tensors on top of each other
y = torch.stack([x, x, x, x], dim=0)
z = torch.vstack([x, x, x, x])
y, z

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [36]:
y = torch.stack([x, x, x, x], dim=1)
y

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [37]:
y = torch.cat([x, x, x, x], dim= 0)
z = torch.hstack([x, x, x, x])
y, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Squeeze

In [39]:
# Squeeze
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [41]:
z = x_reshaped.squeeze() # Squeeze has no effect since we dont have any empty dimension
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [43]:
x_reshaped_1 = x.reshape(1, 9)
x_reshaped_1, x_reshaped_1.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
z = x_reshaped_1.squeeze() # Squeeze removed empty dimension which is empty
z, z.shape # observe the shape after squeeze. removed all singe dimensions. ex:- (2, 1) -> 2, (2, 1, 2, 1, 2) -> (2, 2, 2)

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
print(f"Original tensor: {x_reshaped_1}")
print(f"Original tensor shape: {x_reshaped_1.shape}")
print()
print(f"Squeezed tensor: {z}")
print(f"Squeezed tensor shape: {z.shape}")

Original tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Original tensor shape: torch.Size([1, 9])

Squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed tensor shape: torch.Size([9])


In [49]:
a = torch.zeros([2, 1, 2, 1, 2])
a, a.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [50]:
b = a.squeeze();
b, b.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

### Unsqueeze

Adds a single dimension to a target tensor at a specific dimension

In [55]:
print(f"Previous squeezed tensor: {z}")
print(f"Previous squeezed tensor shape: {z.shape}")

Previous squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous squeezed tensor shape: torch.Size([9])


In [60]:
# Add an extra dimension with unsqueeze
z_unsqueezed = z.unsqueeze(dim=0)

print(f"Unsqueezed tensor at dim 0: {z_unsqueezed}")
print(f"Unsqueezed tensor shape: {z_unsqueezed.shape}")

Unsqueezed tensor at dim 0: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Unsqueezed tensor shape: torch.Size([1, 9])


In [61]:
# Add an extra dimension at 1 with unsqueeze
z_unsqueezed_1 = z.unsqueeze(dim=1)

print(f"Unsqueezed tensor at dim 1: {z_unsqueezed_1}")
print(f"Unsqueezed tensor shape: {z_unsqueezed_1.shape}")

Unsqueezed tensor at dim 0: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Unsqueezed tensor shape: torch.Size([9, 1])


In [64]:
# Add an extra dimension at 2 with unsqueeze
z_unsqueezed_2 = z.unsqueeze(dim=2)
z_unsqueezed_2, z_unsqueezed_2.shape

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### Permute

Rearranges the dimesions of a target tensor in a specified order - Returns a view of the original tensor with its dimensions permuted
`original tensor shape remains the same`

Reshape - Will not change the original tensor. Return new tensor with different shape `original tensor shape remains the same`

View - Will change the original tensor values. Return a refernce to the original tensor with different shape or same shape. `Original tensor shape remains the same`


Common places `permute` is used in images



In [84]:
x = torch.randn(3, 3)
x

tensor([[-1.1568, -0.5642, -1.2367],
        [-0.2231,  1.9764,  0.1938],
        [-1.6929, -1.2609,  0.7786]])

In [85]:
z = torch.permute(x, (1, 0))
z

tensor([[-1.1568, -0.2231, -1.6929],
        [-0.5642,  1.9764, -1.2609],
        [-1.2367,  0.1938,  0.7786]])

In [86]:
z[0][0] = 9.9999
x, z

(tensor([[ 9.9999, -0.5642, -1.2367],
         [-0.2231,  1.9764,  0.1938],
         [-1.6929, -1.2609,  0.7786]]),
 tensor([[ 9.9999, -0.2231, -1.6929],
         [-0.5642,  1.9764, -1.2609],
         [-1.2367,  0.1938,  0.7786]]))

In [76]:
x = torch.randn(2, 3, 5)
print(x.shape)
z = torch.permute(x, (2, 0 , 1))
print(z.shape)
# (2, 3 ,5) -> (2, 0 , 1) ->
# 2'nd index in original should move to 0,
# 0'th index in orifianl should move to 1,
# 1'st index in original should move to 2

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [79]:
x_image = torch.rand(size=(224, 220, 3)) # [height, width, colour_channel]

# Permute the original image tensor to rearrange the axis (or dim order)
# Change original [height, width, colour_channel] -> [colour_channel, height, width]

x_permuted_image = torch.permute(x_image, (2, 0 , 1)) # [colour_channel, height, width]
print(f"Shape of the image tensor: {x_image.shape}")
print(f"\nShape of the permuted image tensor: {x_permuted_image.shape}")

Shape of the image tensor: torch.Size([224, 220, 3])

Shape of the permuted image tensor: torch.Size([3, 224, 220])
