<a href="https://colab.research.google.com/github/sayanarajasekhar/PyTorch/blob/main/PyTorch_60_minute_Blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the input and outputs of a model, as well as the model's parameters.
<br><br>

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPU's or other specialized hardware to accelerate computing.

In [1]:
# Import PyTorch and NumPy
import torch
import numpy as np

In [2]:
torch.__version__

'2.9.0+cu126'

In [3]:
np.__version__

'2.0.2'

## Tensor Initialization

Tensors can be initialized in various ways

### **Directly from data**

Tensors can be created directly from data. The data type is automatically infered.

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# Data type of tensor
x_data.dtype

torch.int64

In [7]:
# Shape of tensor
x_data.shape

torch.Size([2, 2])

### **From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see [Bridge with NumPy](https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label))

In [8]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
x_np

[[1 2]
 [3 4]]


tensor([[1, 2],
        [3, 4]])

### **From another tensor**

The new tensor retains the properties (`shape`, `datatype`) of the argument tensor, unless explicitly orverridden

In [10]:
# Create ones tensor simillar to x_data
x_ones = torch.ones_like(x_data) # Retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# Create zero tensor simillar to x_data
x_zeros = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zeros} \n")

# Create random tensor simillar to x_data
x_rand = torch.rand_like(x_data, dtype = torch.float) # Changing the data type to float
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.9260, 0.8862],
        [0.9728, 0.0405]]) 



### **With random or constant values**

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor

In [12]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.9040, 0.6544, 0.2211],
        [0.4167, 0.7508, 0.1935]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: n tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor Attributes

Tensor attributes describes their shape, datatype and the device on which they are stored

In [14]:
tensor = torch.rand(3, 4)
print(f"Tensor: \n {tensor} \n")

# Attributes
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Tensor: 
 tensor([[0.1571, 0.8315, 0.6604, 0.9592],
        [0.6091, 0.5974, 0.2885, 0.5066],
        [0.6048, 0.3597, 0.1703, 0.9215]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tesnor Operations

Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).
<br><br>
Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Edit > Notebook Settings.

In [3]:
import torch

tensor = torch.rand(3, 4)

# We move our tensor to GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### **Standard numpy-like indexing and slicing**

In [11]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### **Joining tensors**

You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also [`torch.stack`](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joing operation that is subtly different from `torch.cat`

In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(f"Shape: {tensor.shape}")
print(f"Shape: {t1.shape}")

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
Shape: torch.Size([4, 4])
Shape: torch.Size([4, 12])


In [19]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)
print(f"Shape: {tensor.shape}")
print(f"Shape: {t2.shape}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Shape: torch.Size([4, 4])
Shape: torch.Size([12, 4])


In [20]:
t3 = torch.stack([tensor, tensor, tensor], dim=1)
print(t3)
print(f"Shape: {tensor.shape}")
print(f"Shape: {t3.shape}")

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
Shape: torch.Size([4, 4])
Shape: torch.Size([4, 3, 4])


In [21]:
t4 = torch.stack([tensor, tensor, tensor], dim=0)
print(t4)
print(f"Shape: {tensor.shape}")
print(f"Shape: {t4.shape}")

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
Shape: torch.Size([4, 4])
Shape: torch.Size([3, 4, 4])


### **Multiplying tensors**

Element-wise product

In [22]:
# This computs the element-wise product
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n ")

# Alternative syntax:
print(f"tensor * tensor: \n {tensor * tensor} \n")

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 
tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



Matrix multiplication

In [23]:
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")

# Alternative syntax
print(f"tensor @ tensor.T: \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



## In-place operations

Operations that have a `_` suffix are in-place.

For example: `x.copy_(y)`, `x.t_()`, will change `x`

In [24]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


> Note: In-place operations save some memory, but can be problematic when computing derivatives beacause of an immediate loss of history, Hence, their use is discouraged.

## Bridge with NumPy

Tensors on the CPU and NumPY arrays can share their underlying memory locations, and changing one will change the other.

### **Tensor to NumPy array**

In [10]:
import torch
import numpy as np

In [5]:
torch.cuda.is_available()

False

In [8]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A Change in tensor reflects in the NumPy array

In [9]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### **NumPy array to Tensor**

In [11]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor

In [12]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
